version: "3"

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: iot-project
      POSTGRES_PASSWORD: iot-project
      POSTGRES_DB: iot-project
    ports:
      - "5432:5432"